"""empty message

Revision ID: 076c0c84ecee
Revises: None
Create Date: 2016-07-22 15:07:27.668578

"""

# revision identifiers, used by Alembic.
revision = '076c0c84ecee'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    ### end Alembic commands ###
