"""empty message

Revision ID: 41a4d71d0da0
Revises: 076c0c84ecee
Create Date: 2016-07-25 11:33:16.539408

"""

# revision identifiers, used by Alembic.
revision = '41a4d71d0da0'
down_revision = '076c0c84ecee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('field_data', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'history_pkey')
    )
    ### end Alembic commands ###
