"""empty message

Revision ID: 7482a7145e58
Revises: 41a4d71d0da0
Create Date: 2016-07-25 12:42:26.878058

"""

# revision identifiers, used by Alembic.
revision = '7482a7145e58'
down_revision = '41a4d71d0da0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nzbfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workQueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workQueue')
    op.drop_table('nzbfile')
    op.drop_table('history')
    ### end Alembic commands ###
